version: '3.8'

services:
  tzfanim-search:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=sqlite:////tmp/db.sqlite
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - MAX_WORKERS=8  # Optimized for c5.4xlarge with 16 vCPUs
      - BATCH_SIZE_MULTIPLIER=200  # Increased for c5.4xlarge with 16 vCPUs
      - REDIS_POOL_SIZE=40
      - REDIS_MAX_CONNECTIONS=80
      - PROMETHEUS_METRICS=true
      - USE_BOOK_PARALLEL_SEARCH=true  # Enable book-based parallel search
    volumes:
      - ./torah.txt:/app/torah.txt:ro
      - sqlite-data:/tmp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - tzfanim-network

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.tasks.celery_app worker --loglevel=info --concurrency=8
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=sqlite:////tmp/db.sqlite
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP=true
      - USE_BOOK_PARALLEL_SEARCH=true  # Enable book-based parallel search
    volumes:
      - ./torah.txt:/app/torah.txt:ro
      - sqlite-data:/tmp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    networks:
      - tzfanim-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./favicon.ico:/app/favicon.ico:ro
    depends_on:
      - tzfanim-search
    restart: unless-stopped
    networks:
      - tzfanim-network

volumes:
  sqlite-data:

networks:
  tzfanim-network:
    driver: bridge
